# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe1', models.CharField(default='', max_length=9999)),
                ('cafe2', models.CharField(default='', max_length=9999)),
                ('cafe3', models.CharField(default='', max_length=9999)),
                ('cafe4', models.CharField(default='', max_length=9999)),
                ('cafe5', models.CharField(default='', max_length=9999)),
                ('cafe6', models.CharField(default='1', max_length=9999)),
            ],
        ),
    ]
